INSERT INTO authors (full_name) VALUES
                                    ('Jane Austen'),
                                    ('F. Scott Fitzgerald'),
                                    ('Leo Tolstoy'),
                                    ('George Orwell'),
                                    ('Ernest Hemingway'),
                                    ('Mark Twain'),
                                    ('Charles Dickens'),
                                    ('J.K. Rowling'),
                                    ('Harper Lee'),
                                    ('Gabriel Garcia Marquez'),
                                    ('Victor Hugo'),
                                    ('Herman Melville'),
                                    ('Virginia Woolf'),
                                    ('Ray Bradbury'),
                                    ('Toni Morrison'),
                                    ('J.R.R. Tolkien'),
                                    ('Albert Camus'),
                                    ('William Faulkner'),
                                    ('Kazuo Ishiguro'),
                                    ('Chinua Achebe'),
                                    ('Emily Brontë'),
                                    ('Oscar Wilde'),
                                    ('Charlotte Brontë'),
                                    ('Fyodor Dostoevsky'),
                                    ('H.G. Wells'),
                                    ('John Steinbeck'),
                                    ('George Eliot');

INSERT INTO books (isbn, publication_year, title) VALUES
                                                      (9780140430106, 1813, 'Pride and Prejudice'),
                                                      (9780743273565, 1925, 'The Great Gatsby'),
                                                      (9781853262715, 1877, 'Anna Karenina'),
                                                      (9780451524935, 1949, '1984'),
                                                      (9780684801469, 1926, 'The Sun Also Rises'),
                                                      (9781595400324, 1884, 'The Adventures of Huckleberry Finn'),
                                                      (9780141439563, 1859, 'A Tale of Two Cities'),
                                                      (9781408855652, 2003, 'Harry Potter and the Order of the Phoenix'),
                                                      (9780061120084, 1960, 'To Kill a Mockingbird'),
                                                      (9788437613216, 1967, 'Cien años de soledad'),
                                                      (9780140447685, 1862, 'Les Misérables'),
                                                      (9780553213501, 1851, 'Moby-Dick'),
                                                      (9780099511668, 1925, 'Mrs. Dalloway'),
                                                      (9781451673319, 1953, 'Fahrenheit 451'),
                                                      (9780099549487, 1970, 'The Bluest Eye'),
                                                      (9780547928227, 1954, 'The Lord of the Rings'),
                                                      (9780679420262, 1942, 'The Stranger'),
                                                      (9780679732242, 1930, 'As I Lay Dying'),
                                                      (9780571332751, 2005, 'Never Let Me Go'),
                                                      (9780385474542, 1958, 'Things Fall Apart'),
                                                      (9780141439570, 1847, 'Wuthering Heights'),
                                                      (9780199536061, 1891, 'The Picture of Dorian Gray'),
                                                      (9780141441146, 1847, 'Jane Eyre'),
                                                      (9781840227316, 1866, 'Crime and Punishment'),
                                                      (9781593082032, 1897, 'The Invisible Man'),
                                                      (9780140187398, 1939, 'The Grapes of Wrath'),
                                                      (9780140438935, 1871, 'Middlemarch');

INSERT INTO books_authors (book_id, author_id) VALUES
                                                           (1, 1),
                                                           (2, 2),
                                                           (3, 3), (3, 25),
                                                           (4, 4),
                                                           (5, 5),
                                                           (6, 6),
                                                           (7, 7),
                                                           (8, 8),
                                                           (9, 9),
                                                           (10, 10),
                                                           (11, 11),
                                                           (12, 12),
                                                           (13, 13),
                                                           (14, 14),
                                                           (15, 15),
                                                           (16, 16),
                                                           (17, 17),
                                                           (18, 18),
                                                           (19, 19),
                                                           (20, 20),
                                                           (20, 21),
                                                           (21, 21),
                                                           (22, 22),
                                                           (23, 23),
                                                           (24, 24),
                                                           (25, 25);

INSERT INTO quotes (likes, page_number, text, book_id, user_id) VALUES
                                                                    (0, 23, 'It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.', 1, 1),
                                                                    (0, 112, 'So we beat on, boats against the current, borne back ceaselessly into the past.', 2, 1),
                                                                    (0, 107, 'All happy families are alike; each unhappy family is unhappy in its own way.', 3, 1),
                                                                    (0, 1, 'It was a bright cold day in April, and the clocks were striking thirteen.', 4, 1),
                                                                    (0, 10, 'You can''t repeat the past.', 2, 1),
                                                                    (0, 7, 'Persons attempting to find a motive in this narrative will be prosecuted; persons attempting to find a moral in it will be banished; persons attempting to find a plot in it will be shot.', 6, 1),
                                                                    (0, 215, 'It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness...', 7, 1),
                                                                    (0, 50, 'The hottest day of the summer so far was drawing to a close and a drowsy silence lay over the large, square houses of Privet Drive.', 8, 1),
                                                                    (0, 278, 'Mockingbirds don’t do one thing but make music for us to enjoy. They don’t eat up people’s gardens, don’t nest in corn cribs, they don’t do one thing but sing their hearts out for us. That’s why it’s a sin to kill a mockingbird.', 9, 1),
                                                                    (0, 1, 'Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo.', 10, 1),
                                                                    (0, 1, 'To love another person is to see the face of God.', 11, 1),
                                                                    (0, 1, 'Call me Ishmael.', 12, 1),
                                                                    (0, 1, 'Mrs. Dalloway said she would buy the flowers herself.', 13, 1),
                                                                    (0, 1, 'It was a pleasure to burn.', 14, 1),
                                                                    (0, 1, 'Love is patient, love is kind.', 15, 1),
                                                                    (0, 1, 'The road to hell is paved with good intentions.', 16, 1),
                                                                    (0, 1, 'The past is never dead. It''s not even past.', 17, 1),
                                                                    (0, 1, 'Memory is the diary we all carry about with us.', 18, 1),
                                                                    (0, 1, 'The only thing necessary for the triumph of evil is for good men to do nothing.', 19, 1),
                                                                    (0, 1, 'There was a boy called Eustace Clarence Scrubb, and he almost deserved it.', 20, 1),
                                                                    (0, 1, 'I am Heathcliff!', 21, 1),
                                                                    (0, 1, 'The only way to get rid of a temptation is to yield to it.', 22, 1),
                                                                    (0, 1, 'I am no bird; and no net ensnares me: I am a free human being with an independent will.', 23, 1),
                                                                    (0, 1, 'Pain and suffering are always inevitable for a large intelligence and a deep heart.', 24, 1),
                                                                    (0, 1, 'Adventures are good things, you know.', 25, 1);